config/routes.rb
OAONLINE::Application.routes.draw do
  resources :menu_to_roles

  resources :menus

  resources :roles

  resources :posts

  resources :users

  resources :login

  resources :departments

  resources :companies

  resources :index

  get "user_login" => "user_login#user_login"

  get "e_login" => "e_login#e_login"

  post "dounionlogin" => "login#dounionlogin"
  get "e_dounionlogin" => "login#e_dounionlogin"

  post "enter_dounionlogin"=>"login#enter_dounionlogin"

  get "reg" => "companies#new"

  get "find_first_level_menu" =>"menus#find_first_level_menu"

  root 'login#login'

  

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :departments

  def self.login(enterprise,password)
    find(:first,
         :conditions => ["username = ? and password = ?",
                         enterprise, password])
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  def self.find_menus_items
    Menu.all.each.collect {|item|[item.name,item.id]}
  end
  def self.find_first_level_menu
    @first_menus = Menu.where(:level => 0).all
  end

  def self.find_second_level_menu(parentID)
    Menu.where(:parent_id => parentID).all
  end
end

app/models/menu_to_role.rb
class MenuToRole < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :roles

  def self.login(name, password)
    find(:first,
         :conditions => ["name = ? and password = ?",
                         name, password])
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    cont = params[:controller];
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    cont = params[:controller];
  end

  # GET /companies/new
  def new
    @company = Company.new
    render :layout => "blank"
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :phone, :address, :email, :fax, :description, :level)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index

  end
end

app/controllers/login_controller.rb
require File.expand_path('../../Tool/result',__FILE__)
class LoginController < ApplicationController
  layout "blank"
  def dounionlogin
      if request.get?
        session[:user_id] = nil
      else
        @user = User.login(params[:user][:name],params[:user][:password])
        if @user
          session[:user_id] = @user.id
          redirect_to controller: 'index',action: 'index'
        else
          flash[:notice] = "Error username or passwprd"
          render 'login',alert: "Error username or passwprd"
        end
      end
  end

  def e_dounionlogin
    render "e_login"
  end

  def enter_dounionlogin
    if request.get?
      session[:company_id] = nil
    else
      @company = Company.login(params[:enterprise_name],params[:enterprise_pass])
      if @company
        session[:company_id] = @company.id
        redirect_to controller: 'index',action: 'index'
      else
        flash[:notice] = "Error username or passwprd"
        render 'login',alert: "Error username or passwprd"
      end
    end
  end
end

app/controllers/reg_controller.rb
class RegController < ApplicationController
  def reg
    render :layout => "blank"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/e_login_helper.rb
module ELoginHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reg_helper.rb
module RegHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_login_helper.rb
module UserLoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_department_list.html.erb
<h1>Listing departments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cid</th>
      <th>Chargeuserid</th>
      <th>Desc</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= department.company_id %></td>
        <td><%= department.chargeuserid %></td>
        <td><%= department.desc %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
   <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
   </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :fax %><br>
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/_new_department.html.erb
<h1>New department</h1>

<%= form_for(department) do |f| %>
    <% if department.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

          <ul>
            <% department.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :chargeuserid %><br>
      <%= f.text_field :chargeuserid %>
    </div>
    <div class="field">
      <%= f.label :desc %><br>
      <%= f.text_area :desc %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Email</th>
      <th>Fax</th>
      <th>Description</th>
      <th>Level</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.phone %></td>
        <td><%= company.address %></td>
        <td><%= company.email %></td>
        <td><%= company.fax %></td>
        <td><%= company.description %></td>
        <td><%= company.level %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @company.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company.email %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @company.fax %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>

<p>
  <strong>Level:</strong>
  <%= @company.level %>
</p>
<%= render :partial => "department_list", :locals => { :departments => @company.departments}%>
<%= render :partial => "new_department", :locals=>{ :department => Department.new } %>
<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>